---
- name: install dependencies
  yum: name={{ item }}
  with_items: shadowsocks_dependencies
  tags: prepare

- name: install pip
  easy_install: name=pip
  tags: prepare

- name: install Shadowsocks
  pip: name=shadowsocks state=latest
  tags: install

- name: generate a random password
  command: openssl rand -base64 18
  register: shadowsocks_password
  when: shadowsocks.dynamic_password
  tags: config

- name: output password for reference
  debug: msg="{{ shadowsocks_password.stdout }}"
  when: shadowsocks.dynamic_password
  tags: config

- name: generate config file
  template: src=shadowsocks.json
            dest={{ shadowsocks.home }}/shadowsocks.json
            owner=shadowsocks
            group=shadowsocks
            mode=640
  notify: restart shadowsocks
  tags: config

- name: generate init script
  template: src=shadowsocks.init
            dest=/etc/init.d/shadowsocks
            owner=root
            group=root
            mode=755
  tags: config

- name: tweak sysctl
  sysctl: name="{{ item.key }}"
          value="{{ item.value }}"
          state=present
          reload=yes
          ignoreerrors=yes
  with_items: shadowsocks.sysctl.params
  when: shadowsocks.sysctl.tweak
  tags: sysctl

- name: enable tcp_fastopen if available
  sysctl: name="net.ipv4.tcp_fastopen"
          value="3"
          state=present
          reload=yes
  when: shadowsocks.sysctl.tweak and ansible_kernel | version_compare('3.7', '>=')
  tags: sysctl

- name: start and enable service
  service: name=shadowsocks
           state=started
           enabled=yes
