---
- name: include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}.yml"
   - "main.yml"

- name: include OS-specific roles
  include: CentOS.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6
